QUESTIONS = {
  question_0: {
    content: 'What type of sport do you want to engage in?',
    answers: {
      a: {
        content: 'Racket: you’re looking for something you can swing or hit at',
        points: {
          "Archery" =>  0,
          "Badminton" =>  5,
          "Basketball" => 0,
          "Boxing" => 5,
          "Climbing" => 0,
          "Cycling" =>  0,
          "Dodgeball" =>  3,
          "Fencing" =>  0,
          "Field Hockey" => 5,
          "Football" => 1,
          "Golf" => 5,
          "Handball" => 0,
          "Horse Riding" => 0,
          "Korfball" => 0,
          "Krav Maga" =>  5,
          "Kung Fu" =>  5,
          "Quidditch" =>  0,
          "Rowing" => 0,
          "Rugby" =>  5,
          "Running" =>  0,
          "Sailing" =>  0,
          "Squash" => 5,
          "Surfing" =>  0,
          "Swimming" => 0,
          "Table Tennis" => 3,
          "Tennis" => 3,
          "Ultimate Frisbee" => 0,
          "Volleyball" => 3,
          "Water Polo" => 0,
          "Wrestling" =>  3,
          "Yoga" => 0
        }
      },
      b: {
        content: 'Adventure : you’re looking for something unconventional',
        points: {
          "Archery" =>  3,
          "Badminton" =>  3,
          "Basketball" => 0,
          "Boxing" => 0,
          "Climbing" => 0,
          "Cycling" =>  3,
          "Dodgeball" =>  5,
          "Fencing" =>  5,
          "Field Hockey" => 3,
          "Football" => 0,
          "Golf" => 0,
          "Handball" => 3,
          "Horse Riding" => 3,
          "Korfball" => 3,
          "Krav Maga" =>  5,
          "Kung Fu" =>  5,
          "Quidditch" =>  5,
          "Rowing" => 0,
          "Rugby" =>  0,
          "Running" =>  0,
          "Sailing" =>  3,
          "Squash" => 3,
          "Surfing" =>  3,
          "Swimming" => 0,
          "Table Tennis" => 0,
          "Tennis" => 0,
          "Ultimate Frisbee" => 5,
          "Volleyball" => 3,
          "Water Polo" => 5,
          "Wrestling" =>  5,
          "Yoga" => 0
        }
      },
      c: {
        content: 'Veteran: I prefer something typical that I already know',
        points: {
          "Archery" =>  0,
          "Badminton" =>  0,
          "Basketball" => 5,
          "Boxing" => 3,
          "Climbing" => 3,
          "Cycling" =>  3,
          "Dodgeball" =>  3,
          "Fencing" =>  0,
          "Field Hockey" => 0,
          "Football" => 5,
          "Golf" => 5,
          "Handball" => 0,
          "Horse Riding" => 0,
          "Korfball" => 0,
          "Krav Maga" =>  0,
          "Kung Fu" =>  0,
          "Quidditch" =>  0,
          "Rowing" => 0,
          "Rugby" =>  0,
          "Running" =>  0,
          "Sailing" =>  0,
          "Squash" => 0,
          "Surfing" =>  0,
          "Swimming" => 5,
          "Table Tennis" => 3,
          "Tennis" => 5,
          "Ultimate Frisbee" => 0,
          "Volleyball" => 3,
          "Water Polo" => 0,
          "Wrestling" =>  0,
          "Yoga" => 5
        }
      }
    }
  },
  question_1: {
    content: 'How intense do you want your workout to be?',
    answers: {
      a: {
        content: 'Give me all you got ',
        points: {
          "Archery" =>  0,
          "Badminton" =>  3,
          "Basketball" => 3,
          "Boxing" => 5,
          "Climbing" => 5,
          "Cycling" =>  5,
          "Dodgeball" =>  3,
          "Fencing" =>  3,
          "Field Hockey" => 3,
          "Football" => 3,
          "Golf" => 0,
          "Handball" => 3,
          "Horse Riding" => 0,
          "Korfball" => 3,
          "Krav Maga" =>  3,
          "Kung Fu" =>  3,
          "Quidditch" =>  3,
          "Rowing" => 3,
          "Rugby" =>  5,
          "Running" =>  0,
          "Sailing" =>  0,
          "Squash" => 3,
          "Surfing" =>  0,
          "Swimming" => 5,
          "Table Tennis" => 3,
          "Tennis" => 3,
          "Ultimate Frisbee" => 3,
          "Volleyball" => 3,
          "Water Polo" => 5,
          "Wrestling" =>  3,
          "Yoga" => 0
        }
      },
      b: {
        content: 'I want to challenge myself but not completely overdo it',
        points: {
          "Archery" =>  3,
          "Badminton" =>  5,
          "Basketball" => 5,
          "Boxing" => 3,
          "Climbing" => 3,
          "Cycling" =>  3,
          "Dodgeball" =>  5,
          "Fencing" =>  5,
          "Field Hockey" => 5,
          "Football" => 5,
          "Golf" => 3,
          "Handball" => 5,
          "Horse Riding" => 3,
          "Korfball" => 5,
          "Krav Maga" =>  5,
          "Kung Fu" =>  5,
          "Quidditch" =>  5,
          "Rowing" => 5,
          "Rugby" =>  3,
          "Running" =>  0,
          "Sailing" =>  3,
          "Squash" => 5,
          "Surfing" =>  3,
          "Swimming" => 3,
          "Table Tennis" => 5,
          "Tennis" => 5,
          "Ultimate Frisbee" => 5,
          "Volleyball" => 5,
          "Water Polo" => 3,
          "Wrestling" =>  5,
          "Yoga" => 5
        }
      },
      c: {
        content: 'I prefer something with little effort',
        points: {
          "Archery" =>  5,
          "Badminton" =>  3,
          "Basketball" => 0,
          "Boxing" => 0,
          "Climbing" => 0,
          "Cycling" =>  0,
          "Dodgeball" =>  0,
          "Fencing" =>  0,
          "Field Hockey" => 0,
          "Football" => 0,
          "Golf" => 5,
          "Handball" => 0,
          "Horse Riding" => 5,
          "Korfball" => 0,
          "Krav Maga" =>  0,
          "Kung Fu" =>  0,
          "Quidditch" =>  0,
          "Rowing" => 0,
          "Rugby" =>  0,
          "Running" =>  0,
          "Sailing" =>  5,
          "Squash" => 0,
          "Surfing" =>  5,
          "Swimming" => 0,
          "Table Tennis" => 0,
          "Tennis" => 0,
          "Ultimate Frisbee" => 0,
          "Volleyball" => 0,
          "Water Polo" => 0,
          "Wrestling" =>  0,
          "Yoga" => 3
        }
      }
    }
  },
  question_2: {
    content: 'Do you prefer to do sports in teams or by yourself?',
    answers: {
      a: {
        content: 'I prefer working in teams',
        points: {
          "Archery" =>  0,
          "Badminton" =>  0,
          "Basketball" => 50,
          "Boxing" => 0,
          "Climbing" => 0,
          "Cycling" =>  0,
          "Dodgeball" =>  50,
          "Fencing" =>  0,
          "Field Hockey" => 50,
          "Football" => 50,
          "Golf" => 0,
          "Handball" => 50,
          "Horse Riding" => 0,
          "Korfball" => 50,
          "Krav Maga" =>  0,
          "Kung Fu" =>  0,
          "Quidditch" =>  50,
          "Rowing" => 50,
          "Rugby" =>  50,
          "Running" =>  0,
          "Sailing" =>  0,
          "Squash" => 0,
          "Surfing" =>  0,
          "Swimming" => 0,
          "Table Tennis" => 0,
          "Tennis" => 0,
          "Ultimate Frisbee" => 50,
          "Volleyball" => 50,
          "Water Polo" => 50,
          "Wrestling" =>  0,
          "Yoga" => 0
        }
      },
      b: {
        content: 'I don’t mind if I work in a team or by myself',
        points: {
          "Archery" =>  0,
          "Badminton" =>  0,
          "Basketball" => 0,
          "Boxing" => 0,
          "Climbing" => 0,
          "Cycling" =>  0,
          "Dodgeball" =>  0,
          "Fencing" =>  0,
          "Field Hockey" => 0,
          "Football" => 0,
          "Golf" => 0,
          "Handball" => 0,
          "Horse Riding" => 0,
          "Korfball" => 0,
          "Krav Maga" =>  0,
          "Kung Fu" =>  0,
          "Quidditch" =>  0,
          "Rowing" => 0,
          "Rugby" =>  0,
          "Running" =>  0,
          "Sailing" =>  0,
          "Squash" => 0,
          "Surfing" =>  0,
          "Swimming" => 0,
          "Table Tennis" => 0,
          "Tennis" => 0,
          "Ultimate Frisbee" => 0,
          "Volleyball" => 0,
          "Water Polo" => 0,
          "Wrestling" =>  0,
          "Yoga" => 0
        }
      },
      c: {
        content: 'I’m a lonely ranger',
        points: {
          "Archery" =>  50,
          "Badminton" =>  50,
          "Basketball" => 0,
          "Boxing" => 50,
          "Climbing" => 50,
          "Cycling" =>  50,
          "Dodgeball" =>  0,
          "Fencing" =>  50,
          "Field Hockey" => 0,
          "Football" => 0,
          "Golf" => 50,
          "Handball" => 0,
          "Horse Riding" => 50,
          "Korfball" => 0,
          "Krav Maga" =>  50,
          "Kung Fu" =>  50,
          "Quidditch" =>  0,
          "Rowing" => 0,
          "Rugby" =>  0,
          "Running" =>  0,
          "Sailing" =>  50,
          "Squash" => 50,
          "Surfing" =>  50,
          "Swimming" => 50,
          "Table Tennis" => 50,
          "Tennis" => 50,
          "Ultimate Frisbee" => 0,
          "Volleyball" => 0,
          "Water Polo" => 0,
          "Wrestling" =>  50,
          "Yoga" => 50
        }
      }
    }
  },
  question_3: {
    content: 'How much are you willing to spend on sports equipment?',
    answers: {
      a: {
        content: 'I am willing to spend a high amount',
        points: {
          "Archery" =>  0,
          "Badminton" =>  0,
          "Basketball" => 0,
          "Boxing" => 0,
          "Climbing" => 0,
          "Cycling" =>  0,
          "Dodgeball" =>  0,
          "Fencing" =>  0,
          "Field Hockey" => 0,
          "Football" => 0,
          "Golf" => 0,
          "Handball" => 0,
          "Horse Riding" => 0,
          "Korfball" => 0,
          "Krav Maga" =>  0,
          "Kung Fu" =>  0,
          "Quidditch" =>  0,
          "Rowing" => 0,
          "Rugby" =>  0,
          "Running" =>  0,
          "Sailing" =>  0,
          "Squash" => 0,
          "Surfing" =>  0,
          "Swimming" => 0,
          "Table Tennis" => 0,
          "Tennis" => 0,
          "Ultimate Frisbee" => 0,
          "Volleyball" => 0,
          "Water Polo" => 0,
          "Wrestling" =>  0,
          "Yoga" => 0
        }
      },
      b: {
        content: 'I am willing to spend a decent amount',
        points: {
          "Archery" =>  5,
          "Badminton" =>  5,
          "Basketball" => 5,
          "Boxing" => 5,
          "Climbing" => 5,
          "Cycling" =>  3,
          "Dodgeball" =>  0,
          "Fencing" =>  3,
          "Field Hockey" => 3,
          "Football" => 5,
          "Golf" => 3,
          "Handball" => 5,
          "Horse Riding" => 0,
          "Korfball" => 5,
          "Krav Maga" =>  0,
          "Kung Fu" =>  0,
          "Quidditch" =>  5,
          "Rowing" => 3,
          "Rugby" =>  5,
          "Running" =>  0,
          "Sailing" =>  3,
          "Squash" => 5,
          "Surfing" =>  3,
          "Swimming" => 0,
          "Table Tennis" => 5,
          "Tennis" => 5,
          "Ultimate Frisbee" => 5,
          "Volleyball" => 5,
          "Water Polo" => 5,
          "Wrestling" =>  5,
          "Yoga" => 0
        }
      },
      c: {
        content: 'I am not  willing to spend anything',
        points: {
          "Archery" =>  3,
          "Badminton" =>  3,
          "Basketball" => 3,
          "Boxing" => 3,
          "Climbing" => 3,
          "Cycling" =>  0,
          "Dodgeball" =>  50,
          "Fencing" =>  0,
          "Field Hockey" => 0,
          "Football" => 3,
          "Golf" => 0,
          "Handball" => 3,
          "Horse Riding" => 0,
          "Korfball" => 3,
          "Krav Maga" =>  50,
          "Kung Fu" =>  50,
          "Quidditch" =>  3,
          "Rowing" => 0,
          "Rugby" =>  3,
          "Running" =>  0,
          "Sailing" =>  0,
          "Squash" => 3,
          "Surfing" =>  0,
          "Swimming" => 50,
          "Table Tennis" => 3,
          "Tennis" => 0,
          "Ultimate Frisbee" => 3,
          "Volleyball" => 3,
          "Water Polo" => 3,
          "Wrestling" =>  3,
          "Yoga" => 50
        }
      }
    }
  },
  question_4: {
    content: 'In which area do you want to improve by doing sports?',
    answers: {
      a: {
        content: 'I want to build up muscles to increase my strength',
        points: {
          "Archery" =>  3,
          "Badminton" =>  3,
          "Basketball" => 3,
          "Boxing" => 5,
          "Climbing" => 5,
          "Cycling" =>  3,
          "Dodgeball" =>  0,
          "Fencing" =>  0,
          "Field Hockey" => 3,
          "Football" => 3,
          "Golf" => 0,
          "Handball" => 5,
          "Horse Riding" => 3,
          "Korfball" => 3,
          "Krav Maga" =>  5,
          "Kung Fu" =>  5,
          "Quidditch" =>  3,
          "Rowing" => 5,
          "Rugby" =>  5,
          "Running" =>  0,
          "Sailing" =>  3,
          "Squash" => 3,
          "Surfing" =>  3,
          "Swimming" => 5,
          "Table Tennis" => 3,
          "Tennis" => 3,
          "Ultimate Frisbee" => 0,
          "Volleyball" => 3,
          "Water Polo" => 5,
          "Wrestling" =>  5,
          "Yoga" => 3
        }
      },
      b: {
        content: 'I want to increase my endurance',
        points: {
          "Archery" =>  0,
          "Badminton" =>  5,
          "Basketball" => 5,
          "Boxing" => 3,
          "Climbing" => 5,
          "Cycling" =>  5,
          "Dodgeball" =>  5,
          "Fencing" =>  3,
          "Field Hockey" => 5,
          "Football" => 5,
          "Golf" => 0,
          "Handball" => 5,
          "Horse Riding" => 0,
          "Korfball" => 5,
          "Krav Maga" =>  3,
          "Kung Fu" =>  3,
          "Quidditch" =>  3,
          "Rowing" => 5,
          "Rugby" =>  5,
          "Running" =>  5,
          "Sailing" =>  3,
          "Squash" => 5,
          "Surfing" =>  3,
          "Swimming" => 5,
          "Table Tennis" => 5,
          "Tennis" => 5,
          "Ultimate Frisbee" => 3,
          "Volleyball" => 5,
          "Water Polo" => 5,
          "Wrestling" =>  5,
          "Yoga" => 3
        }
      },
      c: {
        content: 'I want to improve my flexibility,  coordination and agility',
        points: {
          "Archery" =>  5,
          "Badminton" =>  0,
          "Basketball" => 0,
          "Boxing" => 0,
          "Climbing" => 3,
          "Cycling" =>  0,
          "Dodgeball" =>  3,
          "Fencing" =>  5,
          "Field Hockey" => 0,
          "Football" => 0,
          "Golf" => 5,
          "Handball" => 5,
          "Horse Riding" => 5,
          "Korfball" => 0,
          "Krav Maga" =>  5,
          "Kung Fu" =>  5,
          "Quidditch" =>  3,
          "Rowing" => 3,
          "Rugby" =>  0,
          "Running" =>  3,
          "Sailing" =>  5,
          "Squash" => 5,
          "Surfing" =>  5,
          "Swimming" => 3,
          "Table Tennis" => 5,
          "Tennis" => 3,
          "Ultimate Frisbee" => 5,
          "Volleyball" => 3,
          "Water Polo" => 3,
          "Wrestling" =>  3,
          "Yoga" => 5
        }
      }
    }
  },
  question_5: {
    content: 'What do you think of sports that requires precision?',
    answers: {
      a: {
        content: 'I am fascinated by sports that require me to hit the mark',
        points: {
          "Archery" =>  50,
          "Badminton" =>  3,
          "Basketball" => 50,
          "Boxing" => 0,
          "Climbing" => 0,
          "Cycling" =>  0,
          "Dodgeball" =>  5,
          "Fencing" =>  5,
          "Field Hockey" => 3,
          "Football" => 3,
          "Golf" => 50,
          "Handball" => 3,
          "Horse Riding" => 0,
          "Korfball" => 50,
          "Krav Maga" =>  0,
          "Kung Fu" =>  0,
          "Quidditch" =>  50,
          "Rowing" => 0,
          "Rugby" =>  0,
          "Running" =>  0,
          "Sailing" =>  0,
          "Squash" => 3,
          "Surfing" =>  0,
          "Swimming" => 0,
          "Table Tennis" => 3,
          "Tennis" => 3,
          "Ultimate Frisbee" => 3,
          "Volleyball" => 3,
          "Water Polo" => 3,
          "Wrestling" =>  0,
          "Yoga" => 0
        }
      },
      b: {
        content: 'Precision is important but sport is about more than just hitting the mark',
        points: {
          "Archery" =>  3,
          "Badminton" =>  5,
          "Basketball" => 3,
          "Boxing" => 0,
          "Climbing" => 0,
          "Cycling" =>  0,
          "Dodgeball" =>  5,
          "Fencing" =>  5,
          "Field Hockey" => 5,
          "Football" => 5,
          "Golf" => 3,
          "Handball" => 5,
          "Horse Riding" => 0,
          "Korfball" => 3,
          "Krav Maga" =>  0,
          "Kung Fu" =>  0,
          "Quidditch" =>  3,
          "Rowing" => 0,
          "Rugby" =>  0,
          "Running" =>  0,
          "Sailing" =>  0,
          "Squash" => 5,
          "Surfing" =>  0,
          "Swimming" => 0,
          "Table Tennis" => 5,
          "Tennis" => 5,
          "Ultimate Frisbee" => 5,
          "Volleyball" => 5,
          "Water Polo" => 5,
          "Wrestling" =>  0,
          "Yoga" => 0
        }
      },
      c: {
        content: 'Targeting precise goals is nothing for me',
        points: {
          "Archery" =>  0,
          "Badminton" =>  0,
          "Basketball" => 0,
          "Boxing" => 50,
          "Climbing" => 50,
          "Cycling" =>  50,
          "Dodgeball" =>  0,
          "Fencing" =>  0,
          "Field Hockey" => 0,
          "Football" => 0,
          "Golf" => 0,
          "Handball" => 0,
          "Horse Riding" => 50,
          "Korfball" => 0,
          "Krav Maga" =>  50,
          "Kung Fu" =>  50,
          "Quidditch" =>  0,
          "Rowing" => 50,
          "Rugby" =>  50,
          "Running" =>  0,
          "Sailing" =>  50,
          "Squash" => 0,
          "Surfing" =>  0,
          "Swimming" => 0,
          "Table Tennis" => 0,
          "Tennis" => 0,
          "Ultimate Frisbee" => 0,
          "Volleyball" => 0,
          "Water Polo" => 0,
          "Wrestling" =>  50,
          "Yoga" => 50
        }
      }
    }
  },
  question_6: {
    content: 'What is your main motivation behind doing sports?',
    answers: {
      a: {
        content: 'I want to relax when doing sports',
        points: {
          "Archery" =>  5,
          "Badminton" =>  0,
          "Basketball" => 0,
          "Boxing" => 0,
          "Climbing" => 0,
          "Cycling" =>  3,
          "Dodgeball" =>  0,
          "Fencing" =>  0,
          "Field Hockey" => 0,
          "Football" => 0,
          "Golf" => 5,
          "Handball" => 0,
          "Horse Riding" => 5,
          "Korfball" => 0,
          "Krav Maga" =>  0,
          "Kung Fu" =>  3,
          "Quidditch" =>  0,
          "Rowing" => 0,
          "Rugby" =>  0,
          "Running" =>  3,
          "Sailing" =>  5,
          "Squash" => 0,
          "Surfing" =>  5,
          "Swimming" => 5,
          "Table Tennis" => 0,
          "Tennis" => 0,
          "Ultimate Frisbee" => 0,
          "Volleyball" => 0,
          "Water Polo" => 0,
          "Wrestling" =>  0,
          "Yoga" => 5
        }
      },
      b: {
        content: 'I want to burn as much calories as possible and get in shape',
        points: {
          "Archery" =>  0,
          "Badminton" =>  0,
          "Basketball" => 0,
          "Boxing" => 0,
          "Climbing" => 0,
          "Cycling" =>  3,
          "Dodgeball" =>  0,
          "Fencing" =>  0,
          "Field Hockey" => 0,
          "Football" => 0,
          "Golf" => 5,
          "Handball" => 0,
          "Horse Riding" => 5,
          "Korfball" => 0,
          "Krav Maga" =>  0,
          "Kung Fu" =>  3,
          "Quidditch" =>  0,
          "Rowing" => 0,
          "Rugby" =>  0,
          "Running" =>  3,
          "Sailing" =>  5,
          "Squash" => 0,
          "Surfing" =>  5,
          "Swimming" => 5,
          "Table Tennis" => 0,
          "Tennis" => 0,
          "Ultimate Frisbee" => 0,
          "Volleyball" => 0,
          "Water Polo" => 0,
          "Wrestling" =>  0,
          "Yoga" => 5
        }
      },
      c: {
        content: 'I want to improve my overall health',
        points: {
          "Archery" =>  0,
          "Badminton" =>  5,
          "Basketball" => 5,
          "Boxing" => 0,
          "Climbing" => 3,
          "Cycling" =>  5,
          "Dodgeball" =>  3,
          "Fencing" =>  3,
          "Field Hockey" => 0,
          "Football" => 3,
          "Golf" => 0,
          "Handball" => 0,
          "Horse Riding" => 0,
          "Korfball" => 3,
          "Krav Maga" =>  3,
          "Kung Fu" =>  3,
          "Quidditch" =>  3,
          "Rowing" => 3,
          "Rugby" =>  0,
          "Running" =>  0,
          "Sailing" =>  0,
          "Squash" => 3,
          "Surfing" =>  0,
          "Swimming" => 5,
          "Table Tennis" => 0,
          "Tennis" => 0,
          "Ultimate Frisbee" => 0,
          "Volleyball" => 0,
          "Water Polo" => 3,
          "Wrestling" =>  3,
          "Yoga" => 5
        }
      }
    }
  },
  question_7: {
    content: 'What is your opinion on playful sports with rules and competition?',
    answers: {
      a: {
        content: 'If the sport is not a game, I don’t want to do it',
        points: {
          "Archery" =>  0,
          "Badminton" =>  50,
          "Basketball" => 50,
          "Boxing" => 0,
          "Climbing" => 0,
          "Cycling" =>  0,
          "Dodgeball" =>  50,
          "Fencing" =>  50,
          "Field Hockey" => 50,
          "Football" => 50,
          "Golf" => 50,
          "Handball" => 50,
          "Horse Riding" => 0,
          "Korfball" => 50,
          "Krav Maga" =>  0,
          "Kung Fu" =>  0,
          "Quidditch" =>  50,
          "Rowing" => 0,
          "Rugby" =>  50,
          "Running" =>  0,
          "Sailing" =>  0,
          "Squash" => 50,
          "Surfing" =>  0,
          "Swimming" => 0,
          "Table Tennis" => 50,
          "Tennis" => 50,
          "Ultimate Frisbee" => 50,
          "Volleyball" => 50,
          "Water Polo" => 50,
          "Wrestling" =>  0,
          "Yoga" => 0
        }
      },
      b: {
        content: 'I don’t really care if playful elements are included in the sport',
        points: {
          "Archery" =>  0,
          "Badminton" =>  0,
          "Basketball" => 0,
          "Boxing" => 0,
          "Climbing" => 0,
          "Cycling" =>  0,
          "Dodgeball" =>  0,
          "Fencing" =>  0,
          "Field Hockey" => 0,
          "Football" => 0,
          "Golf" => 0,
          "Handball" => 0,
          "Horse Riding" => 0,
          "Korfball" => 0,
          "Krav Maga" =>  0,
          "Kung Fu" =>  0,
          "Quidditch" =>  0,
          "Rowing" => 0,
          "Rugby" =>  0,
          "Running" =>  0,
          "Sailing" =>  0,
          "Squash" => 0,
          "Surfing" =>  0,
          "Swimming" => 0,
          "Table Tennis" => 0,
          "Tennis" => 0,
          "Ultimate Frisbee" => 0,
          "Volleyball" => 0,
          "Water Polo" => 0,
          "Wrestling" =>  0,
          "Yoga" => 0
        }
      },
      c: {
        content: 'I rather do sports without rules and playful elements',
        points: {
          "Archery" =>  0,
          "Badminton" =>  0,
          "Basketball" => 0,
          "Boxing" => 50,
          "Climbing" => 50,
          "Cycling" =>  50,
          "Dodgeball" =>  0,
          "Fencing" =>  0,
          "Field Hockey" => 0,
          "Football" => 0,
          "Golf" => 0,
          "Handball" => 0,
          "Horse Riding" => 50,
          "Korfball" => 0,
          "Krav Maga" =>  50,
          "Kung Fu" =>  50,
          "Quidditch" =>  0,
          "Rowing" => 50,
          "Rugby" =>  0,
          "Running" =>  0,
          "Sailing" =>  50,
          "Squash" => 0,
          "Surfing" =>  50,
          "Swimming" => 50,
          "Table Tennis" => 0,
          "Tennis" => 0,
          "Ultimate Frisbee" => 0,
          "Volleyball" => 0,
          "Water Polo" => 0,
          "Wrestling" =>  50,
          "Yoga" => 50
        }
      }
    }
  },
  question_8: {
    content: 'Do you want to do a sport that requires body contact?',
    answers: {
      a: {
        content: 'I enjoy sports where I have lots of physical contact with other people',
        points: {
          "Archery" =>  0,
          "Badminton" =>  0,
          "Basketball" => 5,
          "Boxing" => 5,
          "Climbing" => 0,
          "Cycling" =>  0,
          "Dodgeball" =>  0,
          "Fencing" =>  0,
          "Field Hockey" => 3,
          "Football" => 3,
          "Golf" => 0,
          "Handball" => 5,
          "Horse Riding" => 0,
          "Korfball" => 5,
          "Krav Maga" =>  5,
          "Kung Fu" =>  3,
          "Quidditch" =>  3,
          "Rowing" => 0,
          "Rugby" =>  5,
          "Running" =>  0,
          "Sailing" =>  0,
          "Squash" => 0,
          "Surfing" =>  0,
          "Swimming" => 0,
          "Table Tennis" => 0,
          "Tennis" => 0,
          "Ultimate Frisbee" => 0,
          "Volleyball" => 0,
          "Water Polo" => 5,
          "Wrestling" =>  5,
          "Yoga" => 0
        }
      },
      b: {
        content: 'I am fine with physical contact as long as it is not the whole time',
        points: {
          "Archery" =>  3,
          "Badminton" =>  3,
          "Basketball" => 0,
          "Boxing" => 0,
          "Climbing" => 3,
          "Cycling" =>  3,
          "Dodgeball" =>  3,
          "Fencing" =>  3,
          "Field Hockey" => 5,
          "Football" => 5,
          "Golf" => 3,
          "Handball" => 3,
          "Horse Riding" => 3,
          "Korfball" => 3,
          "Krav Maga" =>  0,
          "Kung Fu" =>  5,
          "Quidditch" =>  5,
          "Rowing" => 3,
          "Rugby" =>  0,
          "Running" =>  3,
          "Sailing" =>  3,
          "Squash" => 3,
          "Surfing" =>  3,
          "Swimming" => 3,
          "Table Tennis" => 3,
          "Tennis" => 3,
          "Ultimate Frisbee" => 3,
          "Volleyball" => 3,
          "Water Polo" => 0,
          "Wrestling" =>  0,
          "Yoga" => 3
        }
      },
      c: {
        content: 'I dislike the idea of having physical contact with other people',
        points: {
          "Archery" =>  50,
          "Badminton" =>  50,
          "Basketball" => 0,
          "Boxing" => 0,
          "Climbing" => 50,
          "Cycling" =>  50,
          "Dodgeball" =>  50,
          "Fencing" =>  50,
          "Field Hockey" => 0,
          "Football" => 0,
          "Golf" => 50,
          "Handball" => 0,
          "Horse Riding" => 50,
          "Korfball" => 0,
          "Krav Maga" =>  0,
          "Kung Fu" =>  0,
          "Quidditch" =>  0,
          "Rowing" => 50,
          "Rugby" =>  0,
          "Running" =>  0,
          "Sailing" =>  50,
          "Squash" => 50,
          "Surfing" =>  50,
          "Swimming" => 50,
          "Table Tennis" => 50,
          "Tennis" => 50,
          "Ultimate Frisbee" => 50,
          "Volleyball" => 50,
          "Water Polo" => 0,
          "Wrestling" =>  0,
          "Yoga" => 50
        }
      }
    }
  },
  question_9: {
    content: 'Do you like sport that includes strategic elements?',
    answers: {
      a: {
        content: 'Games that require extensive strategic thinking really fascinate me',
        points: {
          "Archery" =>  0,
          "Badminton" =>  5,
          "Basketball" => 50,
          "Boxing" => 5,
          "Climbing" => 0,
          "Cycling" =>  0,
          "Dodgeball" =>  50,
          "Fencing" =>  5,
          "Field Hockey" => 50,
          "Football" => 50,
          "Golf" => 5,
          "Handball" => 50,
          "Horse Riding" => 0,
          "Korfball" => 50,
          "Krav Maga" =>  5,
          "Kung Fu" =>  0,
          "Quidditch" =>  50,
          "Rowing" => 3,
          "Rugby" =>  5,
          "Running" =>  0,
          "Sailing" =>  0,
          "Squash" => 5,
          "Surfing" =>  0,
          "Swimming" => 0,
          "Table Tennis" => 5,
          "Tennis" => 5,
          "Ultimate Frisbee" => 50,
          "Volleyball" => 50,
          "Water Polo" => 50,
          "Wrestling" =>  0,
          "Yoga" => 0
        }
      },
      b: {
        content: 'I like strategy but it is not the most important aspect of sport',
        points: {
          "Archery" =>  0,
          "Badminton" =>  0,
          "Basketball" => 0,
          "Boxing" => 0,
          "Climbing" => 0,
          "Cycling" =>  0,
          "Dodgeball" =>  0,
          "Fencing" =>  0,
          "Field Hockey" => 0,
          "Football" => 0,
          "Golf" => 0,
          "Handball" => 0,
          "Horse Riding" => 0,
          "Korfball" => 0,
          "Krav Maga" =>  0,
          "Kung Fu" =>  0,
          "Quidditch" =>  0,
          "Rowing" => 0,
          "Rugby" =>  0,
          "Running" =>  0,
          "Sailing" =>  0,
          "Squash" => 0,
          "Surfing" =>  0,
          "Swimming" => 0,
          "Table Tennis" => 0,
          "Tennis" => 0,
          "Ultimate Frisbee" => 0,
          "Volleyball" => 0,
          "Water Polo" => 0,
          "Wrestling" =>  0,
          "Yoga" => 0
        }
      },
      c: {
        content: 'I prefer sports without strategic elements',
        points: {
          "Archery" =>  50,
          "Badminton" =>  3,
          "Basketball" => 0,
          "Boxing" => 3,
          "Climbing" => 50,
          "Cycling" =>  50,
          "Dodgeball" =>  0,
          "Fencing" =>  0,
          "Field Hockey" => 0,
          "Football" => 0,
          "Golf" => 0,
          "Handball" => 0,
          "Horse Riding" => 3,
          "Korfball" => 0,
          "Krav Maga" =>  3,
          "Kung Fu" =>  3,
          "Quidditch" =>  0,
          "Rowing" => 3,
          "Rugby" =>  0,
          "Running" =>  0,
          "Sailing" =>  3,
          "Squash" => 0,
          "Surfing" =>  50,
          "Swimming" => 50,
          "Table Tennis" => 0,
          "Tennis" => 0,
          "Ultimate Frisbee" => 0,
          "Volleyball" => 0,
          "Water Polo" => 0,
          "Wrestling" =>  0,
          "Yoga" => 50
        }
      }
    }
  }
}
